-- Meghívottak lista feltöltése
-- Futtasd a Supabase SQL Editorban, MIUTÁN az invitees tábla (és invite_round) már létezik.
-- Figyelem: törli a meglévő meghívottakat, majd újra feltölti.

delete from public.invitees;

insert into public.invitees (name, label, invite_round, sort_order)
values
  -- Lilla család (első kör)
  ('Szandra', 'Lilla család', 'first', 10),
  ('Gábor', 'Lilla család', 'first', 20),
  ('Márkó', 'Lilla család', 'first', 30),
  ('Alíz', 'Lilla család', 'first', 40),
  ('Nóci', 'Lilla család', 'first', 50),
  ('Zozi', 'Lilla család', 'first', 60),
  ('Nagyi', 'Lilla család', 'first', 70),
  ('Napa', 'Lilla család', 'first', 80),
  ('Csaba', 'Lilla család', 'first', 90),
  ('Szilvi', 'Lilla család', 'first', 100),
  ('Andriska', 'Lilla család', 'first', 110),
  ('Pepe', 'Lilla család', 'first', 120),
  ('Pepe +1', 'Lilla család', 'first', 130),
  ('Anita', 'Lilla család', 'first', 140),
  ('Marci', 'Lilla család', 'first', 150),
  ('Imike', 'Lilla család', 'first', 160),
  ('Fruzsi', 'Lilla család', 'first', 170),
  ('Madi', 'Lilla család', 'first', 180),
  ('Zsuzsa', 'Lilla család', 'first', 190),
  ('Panka', 'Lilla család', 'first', 200),
  ('Alex', 'Lilla család', 'first', 210),

  -- Lilla barát (első kör)
  ('Réka', 'Lilla barát', 'first', 300),
  ('Laci', 'Lilla barát', 'first', 310),
  ('Bogi', 'Lilla barát', 'first', 320),
  ('Gergő', 'Lilla barát', 'first', 330),
  ('Eszti', 'Lilla barát', 'first', 340),
  ('Eszti +1', 'Lilla barát', 'first', 350),
  ('Talli', 'Lilla barát', 'first', 360),
  ('Kata', 'Lilla barát', 'first', 370),
  ('Boti', 'Lilla barát', 'first', 380),
  ('Uli', 'Lilla barát', 'first', 390),
  ('Geri', 'Lilla barát', 'first', 400),
  ('Timi', 'Lilla barát', 'first', 410),
  ('Heni', 'Lilla barát', 'first', 420),
  ('Gazsi', 'Lilla barát', 'first', 430),
  ('Dorina', 'Lilla barát', 'first', 440),
  ('Levi', 'Lilla barát', 'first', 450),
  ('Rudi', 'Lilla barát', 'first', 460),

  -- Lilla barát (második kör)
  ('Csabi', 'Lilla barát', 'second', 470),
  ('Máté', 'Lilla barát', 'second', 480),
  ('Peti', 'Lilla barát', 'second', 490),
  ('Tomi', 'Lilla barát', 'second', 500),

  -- Közös barát (első kör)
  ('Kati', 'Közös barát', 'first', 600),
  ('Adri', 'Közös barát', 'first', 610),
  ('Judit', 'Közös barát', 'first', 620),
  ('Eszter', 'Közös barát', 'first', 630),
  ('Szabi', 'Közös barát', 'first', 640),
  ('Bence', 'Közös barát', 'first', 650),
  ('Viki', 'Közös barát', 'first', 660),
  ('Brigi', 'Közös barát', 'first', 670),
  ('Csabi', 'Közös barát', 'first', 680),
  ('Emese', 'Közös barát', 'first', 690),
  ('Kristóf', 'Közös barát', 'first', 700),
  ('Szandi', 'Közös barát', 'first', 710),
  ('Tas', 'Közös barát', 'first', 720),
  ('Zsuzsi', 'Közös barát', 'first', 730),
  ('Andi', 'Közös barát', 'first', 740),
  ('Eszter', 'Közös barát', 'first', 750),
  ('Gábor', 'Közös barát', 'first', 760),
  ('Zsófi', 'Közös barát', 'first', 770),
  ('Anikó', 'Közös barát', 'first', 780),
  ('Dávid', 'Közös barát', 'first', 790),
  ('Laura', 'Közös barát', 'first', 800),

  -- Közös barát (második kör)
  ('Pataky Gergő', 'Közös barát', 'second', 810),
  ('Hevér Pisti', 'Közös barát', 'second', 820),
  ('Gyuri', 'Közös barát', 'second', 830),
  ('Saci', 'Közös barát', 'second', 840),
  ('Süle Marci', 'Közös barát', 'second', 850),
  ('Fehérvári Dani', 'Közös barát', 'second', 860),

  -- Norbi barát (első kör)
  ('Pityó', 'Norbi barát', 'first', 900),
  ('Tomi', 'Norbi barát', 'first', 910),
  ('Tomi +1', 'Norbi barát', 'first', 920),
  ('Gergő', 'Norbi barát', 'first', 930),
  ('Gergő +1', 'Norbi barát', 'first', 940),
  ('Balázs', 'Norbi barát', 'first', 950),
  ('Zentai Gréta', 'Norbi barát', 'first', 960),
  ('Zentai Petra', 'Norbi barát', 'first', 970),
  ('Zentai Petra +1', 'Norbi barát', 'first', 980),
  ('Dulka', 'Norbi barát', 'first', 990),
  ('Kása Levi', 'Norbi barát', 'first', 1000),
  ('Kása Levi +1', 'Norbi barát', 'first', 1010),
  ('Vígh Gábor', 'Norbi barát', 'first', 1020),
  ('Kiss Lilla', 'Norbi barát', 'first', 1030),
  ('Pál Norbi', 'Norbi barát', 'first', 1040),
  ('Mogyoróssi Niki', 'Norbi barát', 'first', 1050),

  -- Norbi barát (második kör)
  ('Antal Jani', 'Norbi barát', 'second', 1060),
  ('Petra', 'Norbi barát', 'second', 1070),
  ('Forray Dani', 'Norbi barát', 'second', 1080),
  ('Tömpe Tamás', 'Norbi barát', 'second', 1090),
  ('Bogi', 'Norbi barát', 'second', 1100),
  ('Ili', 'Norbi barát', 'second', 1110),

  -- Norbi család (első kör)
  ('Attila', 'Norbi család', 'first', 1200),
  ('Kitti', 'Norbi család', 'first', 1210),
  ('Kati mama', 'Norbi család', 'first', 1220),
  ('Miki', 'Norbi család', 'first', 1230),
  ('Erzsike', 'Norbi család', 'first', 1240),
  ('Babi mama', 'Norbi család', 'first', 1250),
  ('Miki papa', 'Norbi család', 'first', 1260),
  ('Májercsik Pisti', 'Norbi család', 'first', 1270),
  ('Májercsik Zita', 'Norbi család', 'first', 1280),
  ('Májercsik István', 'Norbi család', 'first', 1290),
  ('Erika', 'Norbi család', 'first', 1300),
  ('Szandra', 'Norbi család', 'first', 1310),
  ('Zoli', 'Norbi család', 'first', 1320),
  ('Lili', 'Norbi család', 'first', 1330),
  ('Caca', 'Norbi család', 'first', 1340),
  ('Éva', 'Norbi család', 'first', 1350),
  ('Noémi', 'Norbi család', 'first', 1360),
  ('Kiss Andris', 'Norbi család', 'first', 1370),
  ('Ircsi', 'Norbi család', 'first', 1380),
  ('Kiss Éva', 'Norbi család', 'first', 1390),
  ('Kiss Éva +1', 'Norbi család', 'first', 1400),
  ('Turóczy Gábor', 'Norbi család', 'first', 1410),
  ('Turóczy Erzsó', 'Norbi család', 'first', 1420),
  ('Turóczy Timi', 'Norbi család', 'first', 1430),
  ('Ancika', 'Norbi család', 'first', 1440),
  ('Laci', 'Norbi család', 'first', 1450),

  -- Norbi család (második kör)
  ('Andrea', 'Norbi család', 'second', 1460),
  ('Zsuzsa', 'Norbi család', 'second', 1470),
  ('Zsuzsa +1', 'Norbi család', 'second', 1480);
